name: Tests CI

on:
  workflow_dispatch:
    push:

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: action/checkout@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: build jar
        run: mvn test